# Generated by Django 2.2.6 on 2020-02-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='luke_num',
            new_name='like_num',
        ),
    ]
