# Generated by Django 2.2.6 on 2020-02-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200226_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
