# Generated by Django 2.2.6 on 2020-02-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_type',
            options={'verbose_name': '博客类型', 'verbose_name_plural': '博客类型'},
        ),
    ]
