# Generated by Django 2.2.6 on 2020-02-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200223_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
        migrations.CreateModel(
            name='ReamNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readed_num', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='关联博客')),
            ],
            options={
                'verbose_name': '阅读数量',
                'verbose_name_plural': '阅读数量',
            },
        ),
    ]
