# Generated by Django 2.2.6 on 2020-02-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200223_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReamNum',
            new_name='ReadNum',
        ),
    ]
