# Generated by Django 2.2.6 on 2020-02-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200223_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
