# Generated by Django 2.2.6 on 2020-02-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_readnum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
