# Generated by Django 2.2.6 on 2020-02-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200223_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-c_time', 'title', 'm_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
